---

    - name: Install the latest pymongo package
      pip: name=pymongo state=latest use_mirrors=no

    - name: Clone submission repository
      git: repo=https://git@github.com/AppyDev/{{ group_names[0] }}.git dest=tool/.

    # - name: Set MONGO variable
    #   set_fact: MONGOUSER="{{lookup('env', 'MONGOUSER')}}" MONGOPWD="{{lookup('env', 'MONGOPWD')}}"
    #   delegate_to: localhost

    # - name: Create user
    #   mongodb_user:
    #     database: admin
    #     name: MONGOUSER
    #     password: MONGOPWD 
    #     state: present 

    - name: Add env variables
      lineinfile:
        dest: /home/ubuntu/.bashrc
        line: "{{ item }}"
      with_items:
        - "export MONGOUSER={{ lookup('env', 'MONGOUSER') }}"
        - "export MONGOPWD={{ lookup('env', 'MONGOPWD') }}"

    - name: Source bashrc
      shell: source /home/ubuntu/.bashrc
      args:
        executable: /bin/bash

    - name: Print env
      debug:
        msg: "{{ lookup('env', 'MONGOUSER') }}"

    - name: Create user
      mongodb_user:
        database: admin
        name: admin
        password: admin 
        state: present    

    - name: npm install
      command: chdir=tool/checkboxio/server-side/site/ npm install

    - name: Replace a line in email.js file
      lineinfile:
        path: /home/ubuntu/tool/checkboxio/server-side/site/node_modules/emailjs/smtp/response.js
        regexp: 'return new SMTPResponse(stream);'    
        line: 'return new SMTPResponse(stream , 1000);'
        backup: yes

    - name: Copy nginx config file
      become: yes
      command: cp tool/checkboxio/local-conf/nginx.conf /etc/nginx/nginx.conf

    - name: Copy nginx default file
      become: yes
      command: cp tool/checkboxio/local-conf/default /etc/nginx/sites-enabled/default

    - name: Restarting nginx
      service:
        name: nginx
        state: restarted

    - name: Install forever
      npm: name=forever global=yes state=present

    - name: Check list of nodejs apps running
      command: forever list
      register: forever_list
      changed_when: false

    - name: Start checkboxio app
      command: forever start -o out.log -e err.log  server.js
      args:
         chdir: tool/checkboxio/server-side/site/
      when: "forever_list.stdout.find('tool/checkboxio/server-side/site/server.js') == -1"
