#!/bin/sh
GIT_WORK_TREE=/home/aparnap/production-www/production-www git checkout -f M3
CRUMB=$(curl -s 'http://192.168.33.10:8090/crumbIssuer/api/xml?xpath=concat(//crumbRequestField,":",//crumb)')
curl -X POST -H "$CRUMB" "http://192.168.33.10:8090/job/checkboxio/build"